/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Bean': { kind: 'OBJECT'; name: 'Bean'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'cropYear': { name: 'cropYear'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'origin': { name: 'origin'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'process': { name: 'process'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'roasts': { name: 'roasts'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Roast'; ofType: null; }; }; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; }; };
    'Boolean': unknown;
    'CreateBeanInput': { kind: 'INPUT_OBJECT'; name: 'CreateBeanInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'origin'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'process'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'cropYear'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'notes'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'shortName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'CreateRoastInput': { kind: 'INPUT_OBJECT'; name: 'CreateRoastInput'; isOneOf: false; inputFields: [{ name: 'beanId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'ambientTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'roastingLevel'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'tastingNotes'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'colourChangeTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'firstCrackTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'roastEndTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'colourChangeTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'firstCrackTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'roastEndTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'developmentTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'developmentPercent'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'totalDuration'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'roastDate'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; defaultValue: null }, { name: 'timeSeriesData'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; defaultValue: null }, { name: 'roastProfileCurve'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; defaultValue: null }, { name: 'fanProfileCurve'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; defaultValue: null }, { name: 'notes'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'DateTime': unknown;
    'FileType': { name: 'FileType'; enumValues: 'KLOG' | 'CSV'; };
    'Float': unknown;
    'ID': unknown;
    'Int': unknown;
    'JSON': unknown;
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'addBeanToLibrary': { name: 'addBeanToLibrary'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UserBean'; ofType: null; }; } }; 'createBean': { name: 'createBean'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UserBean'; ofType: null; }; } }; 'createRoast': { name: 'createRoast'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Roast'; ofType: null; }; } }; 'deleteRoast': { name: 'deleteRoast'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'removeBeanFromLibrary': { name: 'removeBeanFromLibrary'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'toggleRoastSharing': { name: 'toggleRoastSharing'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Roast'; ofType: null; }; } }; 'updateRoast': { name: 'updateRoast'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Roast'; ofType: null; }; } }; 'updateTempUnit': { name: 'updateTempUnit'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; 'updateUserBean': { name: 'updateUserBean'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UserBean'; ofType: null; }; } }; 'uploadRoastLog': { name: 'uploadRoastLog'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UploadRoastResult'; ofType: null; }; } }; 'uploadRoastProfile': { name: 'uploadRoastProfile'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RoastProfile'; ofType: null; }; } }; }; };
    'ProfileDownload': { kind: 'OBJECT'; name: 'ProfileDownload'; fields: { 'content': { name: 'content'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'fileName': { name: 'fileName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'ProfileType': { name: 'ProfileType'; enumValues: 'KAFFELOGIC'; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'downloadProfile': { name: 'downloadProfile'; type: { kind: 'OBJECT'; name: 'ProfileDownload'; ofType: null; } }; 'myBeans': { name: 'myBeans'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UserBean'; ofType: null; }; }; }; } }; 'myRoasts': { name: 'myRoasts'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Roast'; ofType: null; }; }; }; } }; 'previewRoastLog': { name: 'previewRoastLog'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RoastLogPreview'; ofType: null; }; } }; 'roastById': { name: 'roastById'; type: { kind: 'OBJECT'; name: 'Roast'; ofType: null; } }; 'roastByShareToken': { name: 'roastByShareToken'; type: { kind: 'OBJECT'; name: 'Roast'; ofType: null; } }; 'roastsByBean': { name: 'roastsByBean'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Roast'; ofType: null; }; }; }; } }; 'roastsByIds': { name: 'roastsByIds'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Roast'; ofType: null; }; }; }; } }; }; };
    'Roast': { kind: 'OBJECT'; name: 'Roast'; fields: { 'ambientTemp': { name: 'ambientTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'bean': { name: 'bean'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Bean'; ofType: null; }; } }; 'colourChangeTemp': { name: 'colourChangeTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'colourChangeTime': { name: 'colourChangeTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'developmentPercent': { name: 'developmentPercent'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'developmentTime': { name: 'developmentTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'fanProfileCurve': { name: 'fanProfileCurve'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; } }; 'firstCrackTemp': { name: 'firstCrackTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'firstCrackTime': { name: 'firstCrackTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'isShared': { name: 'isShared'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'notes': { name: 'notes'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'roastDate': { name: 'roastDate'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'roastEndTemp': { name: 'roastEndTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'roastEndTime': { name: 'roastEndTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'roastFiles': { name: 'roastFiles'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RoastFile'; ofType: null; }; }; }; } }; 'roastProfile': { name: 'roastProfile'; type: { kind: 'OBJECT'; name: 'RoastProfile'; ofType: null; } }; 'roastProfileCurve': { name: 'roastProfileCurve'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; } }; 'roastingLevel': { name: 'roastingLevel'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'shareToken': { name: 'shareToken'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'tastingNotes': { name: 'tastingNotes'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'timeSeriesData': { name: 'timeSeriesData'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; } }; 'totalDuration': { name: 'totalDuration'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; }; };
    'RoastFile': { kind: 'OBJECT'; name: 'RoastFile'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'fileKey': { name: 'fileKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'fileName': { name: 'fileName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'fileType': { name: 'fileType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'FileType'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'RoastLogPreview': { kind: 'OBJECT'; name: 'RoastLogPreview'; fields: { 'ambientTemp': { name: 'ambientTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'colourChangeTime': { name: 'colourChangeTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'developmentPercent': { name: 'developmentPercent'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'firstCrackTime': { name: 'firstCrackTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'parseWarnings': { name: 'parseWarnings'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; 'profileDesigner': { name: 'profileDesigner'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'profileShortName': { name: 'profileShortName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'roastDate': { name: 'roastDate'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'roastEndTime': { name: 'roastEndTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'roastingLevel': { name: 'roastingLevel'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'suggestedBean': { name: 'suggestedBean'; type: { kind: 'OBJECT'; name: 'UserBean'; ofType: null; } }; 'tastingNotes': { name: 'tastingNotes'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'totalDuration': { name: 'totalDuration'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'RoastProfile': { kind: 'OBJECT'; name: 'RoastProfile'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'fileKey': { name: 'fileKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'fileName': { name: 'fileName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'profileDesigner': { name: 'profileDesigner'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'profileShortName': { name: 'profileShortName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'profileType': { name: 'profileType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'ProfileType'; ofType: null; }; } }; }; };
    'String': unknown;
    'TempUnit': { name: 'TempUnit'; enumValues: 'CELSIUS' | 'FAHRENHEIT'; };
    'UpdateRoastInput': { kind: 'INPUT_OBJECT'; name: 'UpdateRoastInput'; isOneOf: false; inputFields: [{ name: 'ambientTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'roastingLevel'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'tastingNotes'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'colourChangeTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'firstCrackTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'roastEndTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'colourChangeTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'firstCrackTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'roastEndTemp'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'developmentTime'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'developmentPercent'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'totalDuration'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }, { name: 'roastDate'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; defaultValue: null }, { name: 'timeSeriesData'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; defaultValue: null }, { name: 'roastProfileCurve'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; defaultValue: null }, { name: 'fanProfileCurve'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; defaultValue: null }, { name: 'notes'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'UploadRoastProfileInput': { kind: 'INPUT_OBJECT'; name: 'UploadRoastProfileInput'; isOneOf: false; inputFields: [{ name: 'roastId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'fileKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'fileName'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'profileType'; type: { kind: 'ENUM'; name: 'ProfileType'; ofType: null; }; defaultValue: null }]; };
    'UploadRoastResult': { kind: 'OBJECT'; name: 'UploadRoastResult'; fields: { 'parseWarnings': { name: 'parseWarnings'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; 'roast': { name: 'roast'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Roast'; ofType: null; }; } }; }; };
    'User': { kind: 'OBJECT'; name: 'User'; fields: { 'clerkId': { name: 'clerkId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'roasts': { name: 'roasts'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Roast'; ofType: null; }; }; }; } }; 'tempUnit': { name: 'tempUnit'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'TempUnit'; ofType: null; }; } }; 'userBeans': { name: 'userBeans'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UserBean'; ofType: null; }; }; }; } }; }; };
    'UserBean': { kind: 'OBJECT'; name: 'UserBean'; fields: { 'bean': { name: 'bean'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Bean'; ofType: null; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'notes': { name: 'notes'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'shortName': { name: 'shortName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}